package firstgame;

public enum Type {
	PLAYER, GROUND, DIEGROUND, ENEMY, WEAPON, PLATFORM, SPIKE, COIN, ITEM_BLOCK, WATER, BLOCK, COIN_BLOCK,
	MOVE_PLATFORM, DOOR, COIN_GOLD, KEY, LASER, LASERBODY, STAIRS, LEVER, LASERTRIGGER, DOORTOP, TRIGGERBOX, STAR, GEM, FIREBALL, BOSS, SAW, BARNACLE, SHOOT, NEWSTAIRS
}
